"""SO101 gripper collision spheres (auto-generated).

Generated by tools/derive_so101_spheres.py from robot_models/so101/scene.xml.
Do not edit by hand; re-run the tool instead.

6-link model: links 0-4 match oscbf's 5-joint chain (shoulder_pan through
wrist_roll). Link 5 is the gripper joint (moving jaw). The moving jaw sphere
is expressed in the jaw pivot frame and rotates with the gripper angle.

Format:
    positions[link][sphere_idx] = (x, y, z) in the link's local frame
    radii[link][sphere_idx] = radius
    jaw_pivot_in_link4 = position of jaw pivot in oscbf link 4 frame
    jaw_pivot_rot_in_link4 = rotation of jaw pivot in oscbf link 4 frame (at gripper=0)
    jaw_joint_axis = joint axis in jaw pivot frame
"""

so101_collision_data = {
    "positions": (
        (),
        (),
        (),
        (),
        ((-0.010489, -0.000265, -0.101701),),
        ((-0.009476, -0.079114, 0.018995),),
    ),
    "radii": (
        (),
        (),
        (),
        (),
        (0.005000,),
        (0.005000,),
    ),
    "jaw_pivot_in_link4": (0.020200, 0.018799, -0.023401),
    "jaw_pivot_rot_in_link4": (
        (1.000000, 0.000006, 0.000003),
        (0.000003, 0.000010, -1.000000),
        (-0.000006, 1.000000, 0.000010),
    ),
    "jaw_joint_axis": (0.0, 0.0, 1.0),
}
