"""SO101 gripper collision spheres (auto-generated).

Generated by tools/derive_so101_spheres.py from robot_models/so101/scene.xml.
Do not edit by hand; re-run the tool instead.

Format matches oscbf Manipulator.from_urdf(collision_data=...):
    {"positions": tuple[num_links][k][3], "radii": tuple[num_links][k]}
with sphere centers expressed in each link's joint frame.
"""

so101_collision_data = {
    "positions": (
        (),
        (),
        (),
        (),
        ((-0.010489, -0.000265, -0.101701), (0.010723, -0.000095, -0.102521),),
    ),
    "radii": (
        (),
        (),
        (),
        (),
        (0.005000, 0.005000,),
    ),
}
