"""SO101 gripper collision spheres (auto-generated).

Generated by tools/derive_so101_spheres.py from robot_models/so101/scene.xml.
Do not edit by hand; re-run the tool instead.

Format matches oscbf Manipulator.from_urdf(collision_data=...):
    {"positions": tuple[num_links][k][3], "radii": tuple[num_links][k]}
with sphere centers expressed in each link's joint frame.
"""

so101_collision_data = {
    "positions": (
        (),
        (),
        (),
        ((-0.000003, -0.050854, 0.035600), (-0.002616, -0.030259, 0.026508),),
        ((0.004306, 0.006249, -0.023395), (-0.010883, -0.000070, -0.045140), (0.019001, 0.000296, -0.057369),),
    ),
    "radii": (
        (),
        (),
        (),
        (0.012400, 0.019640,),
        (0.012400, 0.029864, 0.010457,),
    ),
}
