"""Derive a gripper-end collision sphere cluster for the SO101.

We approximate the wrist + gripper + moving-jaw geometry with a few spheres so
the workspace-containment CBF can keep the *whole gripper* (not just a single
end-effector point) inside the safe box.

Each MuJoCo `class="collision"` mesh geom on the wrist/gripper/jaw bodies is
replaced by its bounding sphere (center = geom world position at q=0, radius =
`model.geom_rbound`). The world center is then expressed in the corresponding
oscbf joint frame (via oscbf's own forward kinematics at q=0), so the emitted
spheres live in the exact frames the CBF transforms them by.

Run:
    .venv/bin/python tools/derive_so101_spheres.py
which (over)writes ``so101_collision_model.py`` at the repo root.
"""

from __future__ import annotations

from pathlib import Path

import mujoco
import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
SCENE_XML = REPO_ROOT / "robot_models" / "so101" / "scene.xml"
OUTPUT_PY = REPO_ROOT / "so101_collision_model.py"

# MuJoCo body name -> oscbf joint/link index (chain: shoulder_pan, shoulder_lift,
# elbow_flex, wrist_flex, wrist_roll). The URDF variant has a fixed gripper, so
# the moving jaw is rigidly attached to the wrist_roll link (index 4).
BODY_TO_LINK = {
    "wrist": 3,
    "gripper": 4,
    "moving_jaw_so101_v1": 4,
}

COLLISION_GROUP = 3  # class="collision" sets group=3 in the SO101 XML
NUM_LINKS = 5


def _geom_sphere(model, data, geom_id: int) -> tuple[np.ndarray, float]:
    """Fit a sphere to a geom's world geometry.

    For mesh geoms we fit the sphere to the actual vertex centroid (tight), so an
    off-center mesh frame does not inflate the radius. Falls back to the broad-phase
    bounding sphere (`geom_xpos` + `geom_rbound`) for non-mesh geoms.
    """
    geom_xpos = np.array(data.geom_xpos[geom_id], dtype=float)
    if int(model.geom_type[geom_id]) != int(mujoco.mjtGeom.mjGEOM_MESH):
        return geom_xpos, float(model.geom_rbound[geom_id])

    mesh_id = int(model.geom_dataid[geom_id])
    addr = int(model.mesh_vertadr[mesh_id])
    nvert = int(model.mesh_vertnum[mesh_id])
    verts_local = np.array(model.mesh_vert[addr : addr + nvert], dtype=float)
    xmat = np.array(data.geom_xmat[geom_id], dtype=float).reshape(3, 3)
    verts_world = geom_xpos + verts_local @ xmat.T
    centroid = verts_world.mean(axis=0)
    radius = float(np.linalg.norm(verts_world - centroid, axis=1).max())
    return centroid, radius


def _world_collision_spheres() -> list[tuple[int, np.ndarray, float]]:
    """Return (link_idx, world_center, radius) for each gripper collision geom."""
    model = mujoco.MjModel.from_xml_path(str(SCENE_XML))
    data = mujoco.MjData(model)
    mujoco.mj_forward(model, data)  # qpos defaults to 0 -> nominal pose

    spheres: list[tuple[int, np.ndarray, float]] = []
    for geom_id in range(model.ngeom):
        if int(model.geom_group[geom_id]) != COLLISION_GROUP:
            continue
        body_id = int(model.geom_bodyid[geom_id])
        body_name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, body_id)
        if body_name not in BODY_TO_LINK:
            continue
        center, radius = _geom_sphere(model, data, geom_id)
        spheres.append((BODY_TO_LINK[body_name], center, radius))
    return spheres


def _oscbf_joint_world_transforms() -> np.ndarray:
    """oscbf joint->world transforms at q=0, shape (NUM_LINKS, 4, 4)."""
    import jax.numpy as jnp

    from test_so101_real import load_robot  # bare Manipulator.from_urdf, no collision data

    robot = load_robot()
    transforms = np.asarray(robot.joint_to_world_transforms(jnp.zeros(robot.num_joints)))
    return transforms


def derive() -> dict:
    spheres = _world_collision_spheres()
    transforms = _oscbf_joint_world_transforms()

    positions: list[list[tuple[float, float, float]]] = [[] for _ in range(NUM_LINKS)]
    radii: list[list[float]] = [[] for _ in range(NUM_LINKS)]

    for link_idx, world_center, radius in spheres:
        t_world_joint = transforms[link_idx]
        r_wj = t_world_joint[:3, :3]
        p_wj = t_world_joint[:3, 3]
        # express the world center in the joint frame: p_link = R^T (p_world - t)
        p_link = r_wj.T @ (world_center - p_wj)
        positions[link_idx].append(tuple(float(v) for v in p_link))
        radii[link_idx].append(round(radius, 6))

    return {
        "positions": tuple(tuple(p) for p in positions),
        "radii": tuple(tuple(r) for r in radii),
    }


def _format_data(data: dict) -> str:
    lines = [
        '"""SO101 gripper collision spheres (auto-generated).',
        "",
        "Generated by tools/derive_so101_spheres.py from robot_models/so101/scene.xml.",
        "Do not edit by hand; re-run the tool instead.",
        "",
        "Format matches oscbf Manipulator.from_urdf(collision_data=...):",
        '    {"positions": tuple[num_links][k][3], "radii": tuple[num_links][k]}',
        "with sphere centers expressed in each link\'s joint frame.",
        '"""',
        "",
        "so101_collision_data = {",
        '    "positions": (',
    ]
    for link_positions in data["positions"]:
        if not link_positions:
            lines.append("        (),")
        else:
            inner = ", ".join(
                "(" + ", ".join(f"{v:.6f}" for v in pt) + ")" for pt in link_positions
            )
            lines.append(f"        ({inner},),")
    lines.append("    ),")
    lines.append('    "radii": (')
    for link_radii in data["radii"]:
        if not link_radii:
            lines.append("        (),")
        else:
            inner = ", ".join(f"{r:.6f}" for r in link_radii)
            lines.append(f"        ({inner},),")
    lines.append("    ),")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    data = derive()
    OUTPUT_PY.write_text(_format_data(data))
    n = sum(len(r) for r in data["radii"])
    print(f"Wrote {OUTPUT_PY.relative_to(REPO_ROOT)} with {n} spheres:")
    for link_idx, (pos, rad) in enumerate(zip(data["positions"], data["radii"])):
        if rad:
            for p, r in zip(pos, rad):
                print(f"  link {link_idx}: center={np.round(p,4)} r={r:.4f}")


if __name__ == "__main__":
    main()
